FROM fj0rd/rs AS builder

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        libopendht-dev

WORKDIR /src
RUN git clone --depth=1 https://github.com/cloudflare/boringtun.git \
 && cd boringtun \
 && cargo build --release \
 && strip ./target/release/boringtun

RUN git clone --depth=1 https://github.com/manuels/wireguard-p2p.git \
 && cd wireguard-p2p \
 && cargo build --release \
 && strip ./target/release/wireguard-p2p

FROM debian:testing-slim

WORKDIR /app
COPY --from=builder /src/boringtun/target/release/boringtun /usr/local/bin
COPY --from=builder /src/wireguard-p2p/target/release/wireguard-p2p /usr/local/bin

ENV WG_LOG_LEVEL=info \
    WG_THREADS=4 \
    WG_SUDO=1 \
    WG_QUICK_USERSPACE_IMPLEMENTATION=/usr/local/bin

RUN apt-get update \
 && echo "resolvconf resolvconf/linkify-resolvconf boolean false" \
      | debconf-set-selections \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      wireguard-tools iproute2 iptables resolvconf \
      tcpdump libhttp-parser2.9 libjsoncpp24

CMD ["wg-quick", "up", "$1"]
