FROM ubuntu:latest as builder

RUN apt-get update
RUN apt-get install curl -y
RUN curl -L -o /tmp/go.sh https://install.direct/go.sh
RUN chmod +x /tmp/go.sh
RUN /tmp/go.sh

###############################################################################
FROM alpine:latest

###### s6
ARG s6url=https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
RUN apk add --no-cache \
    ca-certificates \
    openssh-client \
    tzdata \
    curl \
    nginx \
    jq

RUN curl --fail --silent -L ${s6url} | tar xzvf - -C /
###### v2ray

COPY --from=builder /usr/bin/v2ray/v2ray /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/v2ctl /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/geoip.dat /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/geosite.dat /usr/bin/v2ray/

RUN set -ex \
  ; apk --no-cache add ca-certificates \
  ; mkdir /var/log/v2ray/ \
  ; chmod +x /usr/bin/v2ray/v2ctl \
  ; chmod +x /usr/bin/v2ray/v2ray \
  \
  ; sed -i '1i\daemon off;' /etc/nginx/nginx.conf \
  ; rm -rf /etc/nginx/sites-available/* \
  ; rm -rf /etc/nginx/sites-enabled/* \
  ; mkdir -p /run/nginx

ENV PATH /usr/bin/v2ray:$PATH
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY server.json /etc/v2ray/config.json


COPY services.d /etc/services.d


ENTRYPOINT [ "/init" ]