FROM nnurphy/v2ray

###### s6
ARG s6url=https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
RUN apk add --no-cache \
    openssh-client \
    tzdata \
    curl \
    nginx \
    jq

RUN curl --fail --silent -L ${s6url} | tar xzvf - -C /

RUN set -ex \
  ; sed -i '1i\daemon off;' /etc/nginx/nginx.conf \
  ; rm -rf /etc/nginx/sites-available/* \
  ; rm -rf /etc/nginx/sites-enabled/* \
  ; mkdir -p /run/nginx

ENV PATH /usr/bin/v2ray:$PATH
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY server.json /etc/v2ray/config.json


COPY services.d /etc/services.d


ENTRYPOINT [ "/init" ]