#!/usr/bin/with-contenv sh


export V2RAY_UUID=$(cat /proc/sys/kernel/random/uuid)
echo "${V2RAY_UUID}" > /.v2ray-uuid
echo "v2ray uuid is \`${V2RAY_UUID}\`"
cat /etc/v2ray/config.json | jq  ".inbounds[0].settings.clients[0].id=\"${V2RAY_UUID}\"" > server.json
mv server.json /etc/v2ray/config.json

echo >&2 "starting v2ray"

exec /usr/bin/v2ray -config=/etc/v2ray/config.json 2>&1
